feat: add interactive module and stuff

diff --git a/workstation b/workstation
--- a/workstation
+++ b/workstation
@@ -1,1 +1,61 @@
-#!/usr/bin/env zsh
+#!/usr/bin/env sh
+
+# Color codes for output
+RED='\033[0;31m'
+GREEN='\033[0;32m'
+NC='\033[0m' # No Color
+
+# Logging functions
+log_info() {
+    echo -e "${GREEN}[INFO]${NC} $1"
+}
+
+log_error() {
+    echo -e "${RED}[ERROR]${NC} $1" >&2
+}
+
+install_brew() {
+	[ ! -e /opt/homebrew/bin/brew ] && \
+		log_info "Installing Brew" && \
+		/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"  fi
+}
+
+install_deps() {
+    if command -v brew &>/dev/null; then
+        [ ! -e /opt/homebrew/bin/ansible ] && \
+    		log_info "Installing Ansible" && \
+		brew install ansible
+        [ ! -e /opt/homebrew/bin/guile ] && \
+    		log_info "Installing Guile" && \
+		brew install guile 
+    elif command -v dnf &>/dev/null; then
+        [ ! -e /usr/bin/ansible ] && \
+    		log_info "Installing Ansible" && \
+		sudo dnf install ansible
+        [ ! -e /usr/bin/guile3.0 ] && \
+    		log_info "Installing Guile" && \
+		sudo dnf install guile30 
+    else
+        log_error "Could Not Detect Package Manager To Install Dependencies"
+        return 1
+    fi
+}
+
+main() {
+	local os
+	os="$(uname)"
+
+  if [[ "$os" == "Darwin" ]]; then
+	install_brew
+	install_deps
+	guile -L . --fresh-auto-compile systems/macos/main.scm "$@"
+  elif [[ "$os" == "Linux" ]]; then
+	install_deps
+	guile -L . --fresh-auto-compile systems/linux/main.scm "$@"
+  else
+    log_error "OS Not Supported"
+    return 1
+  fi
+}
+
+main "$@"
